"""empty message

Revision ID: ba3b516daac2
Revises: 11535c5945b8
Create Date: 2021-02-24 15:04:26.019219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3b516daac2'
down_revision = '11535c5945b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentLikes', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('commentLikes', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('postLikes', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('postLikes', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_modified')
    op.drop_column('users', 'date_created')
    op.drop_column('posts', 'date_modified')
    op.drop_column('posts', 'date_created')
    op.drop_column('postLikes', 'date_modified')
    op.drop_column('postLikes', 'date_created')
    op.drop_column('comments', 'date_modified')
    op.drop_column('comments', 'date_created')
    op.drop_column('commentLikes', 'date_modified')
    op.drop_column('commentLikes', 'date_created')
    # ### end Alembic commands ###
